voteContractCodePath: "../../../../../contracts/vote-contract/src/bin/Debug/net8.0/TomorrowDAO.Contracts.Vote.dll.patched"
governanceContractCodePath: "../../../../../contracts/governance-contract/src/bin/Debug/net8.0/TomorrowDAO.Contracts.Governance.dll.patched"
daoContractCodePath: "../../../../../contracts/dao-contract/src/bin/Debug/net8.0/TomorrowDAO.Contracts.DAO.dll.patched"
electionContractCodePath: "../../../../../contracts/election-contract/src/bin/Debug/net8.0/TomorrowDAO.Contracts.Election.dll.patched"
treasuryContractCodePath: "../../../../../contracts/treasury-contract/src/bin/Debug/net8.0/TomorrowDAO.Contracts.Treasury.dll.patched"
timelockContractCodePath: "../../../../../contracts/timelock-contract/src/bin/Debug/net8.0/TomorrowDAO.Contracts.Timelock.dll.patched"
